---
- name: Playbook to convert an ASCII file to EBCDIC
  hosts: zos
  gather_facts: no
  environment:
      ZOAU_ROOT: "{{zoau_home}}"
      ZOAU_HOME: "{{zoau_home}}"
      PATH: "{{zoau_home}}/bin:{{python_path}}/bin:/bin:."
      LIBPATH: "{{zoau_home}}/lib:{{python_path}}/lib:/lib:/usr/lib:."
      PYTHONPATH: "{{zoau_home}}/lib"
      _BPXK_AUTOCVT: "ON"

  collections: 
    ibm.ibm_zos_core

  tasks: 
    - name: Ping the mainframe, lets see if we can work with it
      zos_ping:
      register: zos_ping_result

    - name: DUmp out the results of the Ping
      debug: 
        var: zos_ping_result
    
    - name: Convert a ASCII file to EBCDIC
      zos_encode: 
        src: ZXP.PUBLIC.INPUT(ANSIBLED)
        dest: Z32542.SOURCE(FRMASCII)
        encoding:
          from: ISO8859-1
          to: IBM-1047

