---
- name: Playbook to convert an ASCII file to EBCDIC
  hosts: zos
  gather_facts: no

  collections: 
    ibm.ibm_zos_core

  tasks: 
    
    - name: Convert a ASCII file to EBCDIC
      zos_convert: 
        src: ZXP.PUBLIC.INPUT(ANSIBLED)
        dest: Z32542.SOURCE(FRMASCII)
        encoding:
          from: ISO8859-1
          to: IBM-1047

