- name: Playbook for ZOS Datasets
  hosts: zos
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  vars:
    tgt_tmp_dir: "/tmp"
    PYZ: "/usr/lpp/IBM/cyp/v3r9/pyz"
    ZOAU: "/usr/lpp/IBM/zoautil"
    ansible_python_interpreter: "{{ PYZ }}/bin/python3"

  tasks: 

    - name: Run the date command
      command: date
      register: the_date

    - name: Display date
      debug: 
        var: the_date
   
