---
- name: Playbook to submit a JCL job from a local file and check the status
  hosts: zos
  gather_facts: no
  environment: "{{ environment_vars }}"

  tasks:

    - name: Submit a job
      ibm.ibm_zos_core.zos_job_submit:
        src: "Z32542.JCL(MERGSORT)"
        location: DATA_SET
        wait_time_s: 60
        return_output: false
      register: job_detail
      ignore_errors: true

    - name: Display job details
      ansible.builtin.debug:
        var: job_detail

      