---
- name: Submit a JCl job on a Z/OS System - Update SNOW Request ticket
  hosts: all
  gather_facts: no
  environment: "{{ environment_vars }}"

  vars:
    sn_username: "{{ lookup('ansible.builtin.env', 'SN_USERNAME') }}"
    sn_instance: "{{ lookup('ansible.builtin.env', 'SN_HOST') }}"

  tasks:

    - name: Display the Vars passed from EDA
      ansible.builtin.debug: 
        msg: > 
          "SNOW REQ: {{ sn_request_number }}"
          "JCL Job to Submit: {{ jcl_job_to_submit }}"
          "Requested By: {{ requester }}"
          "SNOW Catalog Item: {{ sn_catalog_item }}"

    # Update to acknowledge the ticket

    - name: Ping the mainframe to see if we can work with it, update the ticket
      ibm.ibm_zos_core.zos_ping: 
      register: ping_result

    - name: Display the ping result
      debug: 
        msg: "{{ ping_result.ping }}"

    # - name: Retrieve requested item ticket sysid
    #   servicenow.itsm.api_info:
    #     resource: sc_req_item
    #     sysparm_query: numberSTARTSWITH{{ sn_request_number }}
    #   register: result

    # - name: Print the result
    #   ansible.builtin.debug:
    #     var: result

    # - name: Update the SNOW ticket before running the JCL
    #   servicenow.itsm.incident:
    #     state: in_progress
    #     caller: "{{ sn_username }}"
    #     number: "{{ incident_number_cached }}"
    #     other:
    #       work_notes: "System: {{ inventory_hostname }} is responding"
    #   delegate_to: localhost
    #   when: ping_result.ping == "pong"

    - name: Debug 
      ansible.builtin.debug:
        msg: "About to submit JCL Job {{ jcl_job_to_submit }}"

    - name: Submit a JCL job
      ibm.ibm_zos_core.zos_job_submit:
        src: "Z32542.JCL({{ jcl_job_to_submit }})"
        location: data_set
        return_output: true
        wait_time_s: 20
      register: job_detail

    - name: Setting fact `Job Results`
      set_fact:
        job_results: "{{ job_detail.jobs[0]}}"

    - name: Results
      debug:  
        msg: "Job {{ job_results.job_id}} completed with {{ job_results.ret_code.msg }} {{ job_results.ret_code.msg_code }}"

    # - name: Update the SNOW ticket with the JCL Job status
    #   servicenow.itsm.incident:
    #     state: in_progress
    #     caller: "{{ sn_username }}"
    #     number: "{{ incident_number_cached }}"
    #     other:
    #       work_notes: "Job {{ job_results.job_id}} completed with {{ job_results.ret_code.msg }} {{ job_results.ret_code.msg_code }}"
    #   delegate_to: localhost
    #   when: job_results.ret_code.msg_code == "0000"
