---
- name: Playbook to check the status of JCL jobs
  hosts: zos
  gather_facts: no
  environment: "{{ environment_vars }}"
  
  collections: 
    ibm.zos_core

  tasks:

    - name: Query a job 
      zos_job_query:
        job_id: "JOB05281"
