---
- name: Ping a ZOS System using Ansible zos_ping
  hosts: zos_tz
  gather_facts: no
  
  collections: 
    - ibm.ibm_zos_core

  tasks: 

    - name: Ping a ZOS system 
      zos_ping:
      register: result

    - name: Display the ping result
      debug: 
        msg: "{{ result.ping }}"
