---
- name: Playbook to submit a JCL and check the status
  hosts: all
  gather_facts: no
  environment:
    ZOAU_ROOT: "{{zoau_home}}"
    ZOAU_HOME: "{{zoau_home}}"
    PATH: "{{zoau_home}}/bin:{{python_path}}/bin:/bin:."
    LIBPATH: "{{zoau_home}}/lib:{{python_path}}/lib:/lib:/usr/lib:."
    PYTHONPATH: "{{zoau_home}}/lib"
    _BPXK_AUTOCVT: "ON"

  collections: 
    ibm.ibm_zos_core

  tasks:
      
    - name: Submit a job
      zos_job_submit:
        src: "Z32542.JCL(MERGSORT)"
        location: DATA_SET
        return_output: true
        wait_time_s: 20
      register: job_detail

    - name: Debug job_detail
      debug:
        var: job_detail

    - name: Setting fact `Job Results`
      set_fact:
        job_results: "{{ job_detail.jobs[0]}}"

    - name: Results
      debug:  
        msg: "Job {{ job_results.job_id}} completed with {{ job_results.ret_code.msg}}"
