---
- name: Ping a ZOS System using Ansible zos_ping
  hosts: zos
  gather_facts: no
  
  tasks: 

    - name: Ping a ZOS system
      ibm.ibm_zos_core.zos_ping:
      register: result

    - name: Display the ping result
      debug: 
        msg: "{{ result.ping }}"
